[workspace.package]
description = "Quakk is a node based live coding synthesizer"
repository = "https://github.com/Ora9/quakk"
license = "MIT"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = [
    "crates/quakk_new",
    "crates/quakk_cli",
    # "crates/quakk_audio",
    "crates/quakk_app"]
default-members = ["crates/quakk_cli"]

[workspace.lints.rust]
unsafe_code = "forbid"
unused = "allow"
dead_code = "allow"

[workspace.dependencies]
# Workspace dependencies
quakk = { path = "crates/quakk_new" }
# quakk_cli = { path = "crates/quakk_cli" }
# quakk_audio = { path = "crates/quakk_audio" }

# External dependencies
anyhow = "1.0.100"
